name: Node.js CI

on: [push] # Triggers the workflow on push events for all branches

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x] # You can specify Node.js versions to test against

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3 # Updated to v3
        with:
          version: 8 # Specify pnpm version if needed, or remove for latest

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test

  e2e-tests:
    needs: build # Ensures e2e-tests run only after the build job is successful
    runs-on: ubuntu-latest
    if: ${{ success() && matrix.node-version == '20.x' }} # Run only if build succeeded and for Node 20.x

    strategy:
      matrix:
        node-version: [20.x] # E2E tests will run on Node.js 20.x

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright Browsers and dependencies
        run: pnpm exec playwright install --with-deps

      - name: Build application
        run: pnpm build
      
      - name: Run E2E tests
        run: |
          pnpm dev &
          echo "Waiting for server to start..."
          sleep 30 # Wait for 30 seconds for the dev server to start
          echo "Running Playwright tests..."
          pnpm test:e2e

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always() # Upload report even if tests fail
        with:
          name: playwright-report-${{ matrix.node-version }}
          path: playwright-report/
